apiVersion: v1
kind: Secret
metadata:
  name: {{ include "porter.fullname" . }}-api-server-keys
  labels:
    {{- include "porter.labels" . | nindent 4 }}
type: Opaque
data:
  cookie-secrets: {{ .Values.server.cookieSecret | b64enc | quote }}
  db-encryption-key: {{ .Values.server.dbEncryptionKey | b64enc | quote }}
  {{- if .Values.server.oldDBEncryptionKey }}
  {{- if (ne .Values.server.oldDBEncryptionKey "") }}
  old-db-encryption-key: {{ .Values.server.oldDBEncryptionKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.server.newDBEncryptionKey }}
  {{- if (ne .Values.server.newDBEncryptionKey "") }}
  new-db-encryption-key: {{ .Values.server.newDBEncryptionKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  token-encryption-key: {{ .Values.server.tokenEncryptionKey | b64enc | quote }}
