apiVersion: v1
kind: Secret
metadata:
  name: {{ include "porter.fullname" . }}-db-secret
  labels:
    {{- include "porter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  host: {{ include "porter.postgresql.fullname" . | b64enc | quote }}
  name: {{ .Values.postgresql.postgresqlDatabase | default "porter" | b64enc | quote }}
  user: {{ .Values.postgresql.postgresqlUsername | default "postgres" | b64enc | quote }}
  password: {{ .Values.postgresql.postgresqlPassword | default "" | b64enc | quote }}
  {{- else }}
  host: {{ .Values.server.postgres.host | default "" | b64enc | quote }}
  name: {{ .Values.server.postgres.name | default "porter" | b64enc | quote }}
  user: {{ .Values.server.postgres.user | default "postgres" | b64enc | quote }}
  password: {{ .Values.server.postgres.password | default "" | b64enc | quote }}
  {{- end }}