apiVersion: v1
kind: Secret
metadata:
  name: {{ include "porter.fullname" . }}-integration-keys
  labels:
    {{- include "porter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.server.slack.enabled }}
  slack-client-id: {{ .Values.server.slack.clientId | b64enc | quote }}
  slack-client-secret: {{ .Values.server.slack.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.server.githubLogin.enabled }}
  github-client-id: {{ .Values.server.githubLogin.clientId | b64enc | quote }}
  github-client-secert: {{ .Values.server.githubLogin.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.server.githubApp.enabled }}
  github-app-client-id: {{ .Values.server.githubApp.clientId | b64enc | quote }}
  github-app-client-secret: {{ .Values.server.githubApp.clientSecret | b64enc | quote }}
  github-app-webhook-secret: {{ .Values.server.githubApp.webhookSecret | b64enc | quote }}
  github-app-name: {{ .Values.server.githubApp.name | b64enc | quote }}
  github-app-id: {{ .Values.server.githubApp.id | b64enc | quote }}
  github-app-private-key: {{ .Values.server.githubApp.privateKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.server.googleLogin.enabled }}
  google-client-id: {{ .Values.server.googleLogin.clientId | b64enc | quote }}
  google-client-secret: {{ .Values.server.googleLogin.clientSecret | b64enc | quote }}
  google-restricted-domain: {{ .Values.server.googleLogin.restrictedDomain | b64enc | quote }}
  {{- end }}